export const PassengerOutcome = {
  REJECTED_CORRECT: 'REJECTED_CORRECT',
  REJECTED_INCORRECT: 'REJECTED_INCORRECT',
  COMPLETED_CORRECT: 'COMPLETED_CORRECT',
  COMPLETED_INCORRECT: 'COMPLETED_INCORRECT',
  INCOMPLETE: 'INCOMPLETE',
};
